version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./dockers/app/Dockerfile
    image: restful_auth_backend_app
    container_name: restful-auth-backend-app
    ports:
      - 80:4000